on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
           python-version: 3.8 #install the python needed
      - run: pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
      - run: python3 quickstart.py